# Explicit source assembly shared by host development and footprint diagnostics.
include_guard(GLOBAL)

function(xgl_dev_validate_sources)
    foreach(component STATUS BYTES CRC MEMORY CONTAINERS)
        set(variable "XGL_DEV_${component}_SOURCE_DIR")
        set(${variable} "" CACHE PATH "Explicit xgen-${component} development checkout")
        if(NOT ${variable})
            message(FATAL_ERROR "${variable} is required; provide all five component source paths explicitly")
        endif()
        if(NOT IS_ABSOLUTE "${${variable}}" OR NOT EXISTS "${${variable}}/CMakeLists.txt")
            message(FATAL_ERROR "${variable} must be an absolute component source directory containing CMakeLists.txt")
        endif()
    endforeach()
endfunction()

function(xgl_dev_provide_components)
    xgl_dev_validate_sources()

    # Select the union needed by this image and its requested development tools.
    # These are local variables, not forced component cache settings.
    foreach(prefix XGS XGB XGCRC XGM XGCT)
        set(${prefix}_BUILD_TESTS OFF)
        set(${prefix}_ENABLE_COVERAGE OFF)
    endforeach()
    set(XGS_BUILD_STRINGS OFF)
    set(XGCRC_BUILD_CRC8 OFF)
    set(XGCRC_BUILD_CRC16 ON)
    set(XGM_COMPONENTS allocator pool size_class)
    set(XGCT_BUILD_LIST ON)
    set(XGCT_BUILD_BITSET ON)
    set(XGCT_BUILD_RING_BUFFER OFF)
    set(XGCT_BUILD_HASH ON)
    if(XGL_PROFILE STREQUAL "boot")
        set(XGCT_BUILD_HASH OFF)
    endif()
    if(XGL_BUILD_TESTS OR XGL_ALLOW_FALLBACK_MALLOC)
        list(APPEND XGM_COMPONENTS libc_allocator)
    endif()

    foreach(component STATUS BYTES CRC MEMORY CONTAINERS)
        string(TOLOWER "${component}" name)
        add_subdirectory("${XGL_DEV_${component}_SOURCE_DIR}"
            "${CMAKE_CURRENT_BINARY_DIR}/dependencies/${name}")
    endforeach()

    set(required xgs::status xgb::bytes xgcrc::crc16
        xgm::allocator xgm::pool xgm::size_class xgct::list xgct::bitset)
    if(XGCT_BUILD_HASH)
        list(APPEND required xgct::hash)
    endif()
    if("libc_allocator" IN_LIST XGM_COMPONENTS)
        list(APPEND required xgm::libc_allocator)
    endif()
    set(build_targets)
    foreach(target IN LISTS required)
        if(NOT TARGET ${target})
            message(FATAL_ERROR "Explicit development sources did not provide ${target}")
        endif()
        get_target_property(type ${target} TYPE)
        if(NOT type STREQUAL "INTERFACE_LIBRARY")
            get_target_property(actual ${target} ALIASED_TARGET)
            if(NOT actual)
                set(actual "${target}")
            endif()
            list(APPEND build_targets "${actual}")
        endif()
    endforeach()
    set(XGL_SDK_DEPENDENCY_TARGETS "${build_targets}" PARENT_SCOPE)
endfunction()
