set(XGL_PROFILE "full" CACHE STRING "Compiled protocol profile: boot, embedded, full")
set_property(CACHE XGL_PROFILE PROPERTY STRINGS boot embedded full)
if(XGL_PROFILE STREQUAL "boot")
    set(XGL_FEATURE_AUTH 0)
    set(XGL_FEATURE_ROUTE_INDEX 0)
    set(XGL_SECURITY_SESSION_CAPACITY 0)
    set(XGL_FEATURE_FORWARDING 0)
    set(XGL_FEATURE_FRAGMENTATION 0)
    set(XGL_FEATURE_OUT_OF_ORDER 0)
    set(XGL_FEATURE_DIAGNOSTICS 0)
    set(XGL_RELIABLE_BUCKET_COUNT 1)
    set(XGL_BUILD_CONFIG_ID 301)
elseif(XGL_PROFILE STREQUAL "embedded" OR XGL_PROFILE STREQUAL "full")
    set(XGL_FEATURE_AUTH 1)
    set(XGL_FEATURE_ROUTE_INDEX 1)
    set(XGL_SECURITY_SESSION_CAPACITY 16)
    set(XGL_FEATURE_FORWARDING 1)
    set(XGL_FEATURE_FRAGMENTATION 1)
    set(XGL_FEATURE_OUT_OF_ORDER 1)
    set(XGL_FEATURE_DIAGNOSTICS 1)
    set(XGL_RELIABLE_BUCKET_COUNT 32)
    if(XGL_PROFILE STREQUAL "embedded")
        set(XGL_BUILD_CONFIG_ID 302)
        set(XGL_SECURITY_SESSION_CAPACITY 4)
    else()
        set(XGL_BUILD_CONFIG_ID 303)
    endif()
else()
    message(FATAL_ERROR "Unknown XGL_PROFILE '${XGL_PROFILE}'")
endif()
configure_file(cmake/xgl_build_config.h.in generated/xgl/xgl_build_config.h @ONLY)
